### ISSUE TITLE
Replace ReactPHP with Icicle

### ISSUE THREAD

**Issue by andrewvy** [andrewvy/HHVMCraft#22]
https://github.com/icicleio/icicle

Let's try it out. The current implementation isn't too heavily dependent on ReactPHP. Mostly interested in [Icicle's concurrency module.](https://github.com/icicleio/concurrent)

**Comment by lancepioch** [comment]
Here's an idea, why not make the core project separate/abstracted enough, that you can use either.

**Comment by andrewvy** [comment]
Closing this issue because I'm not really wanting to switch frameworks for the time being. :)
