### ISSUE TITLE
Using composer's autoload instead of require?

### ISSUE THREAD

**Issue by lungyiing** [andrewvy/HHVMCraft#3]
Have you considered using composer's autoloading functionality instead of requires for this app?

https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by andrewvy** [comment]
Definitely! I do want to clean it up after I'm done, and autoloading is on that list. :+1:

**Comment by lungyiing** [comment]
@andrewvy nice, I can't wait to see how this project turns out. Best of luck :rocket:

**Comment by andrewvy** [comment]
Thank you! I hope to have a more visual demo by the end of the week(end). :100: 

Added this to my post-completion goals: https://github.com/andrewvy/HHVMCraft/issues/4
