### ISSUE TITLE
Style question?

### ISSUE THREAD

**Issue by lungyiing** [andrewvy/HHVMCraft#6]
```
require "HHVMCraft.Core/Networking/Stream.php";
require "HHVMCraft.Core/Helpers/HexDump.php";
require "HHVMCraft.Core/Entities/PlayerEntity.php";
require "HHVMCraft.Core/Windows/InventoryWindow.php";
require "HHVMCraft.Core/Networking/Packets/ChunkPreamblePacket.php";
require "HHVMCraft.Core/Networking/Packets/ChunkDataPacket.php";
require "HHVMCraft.Core/Networking/Packets/DisconnectPacket.php";
require "HHVMCraft.API/Coordinates2D.php";
```

Any reason why this is here even though composer should be autoloading, also wondering why it's "HHVMCraft.Core" instead of "HHVMCraft\Core".

Just wondering :)

Keep up the good work :+1:

**Comment by andrewvy** [comment]
I'm not familiar with how to setup an autoloading script yet! Any help would be appreciated. :)

About the naming style, it seems redundant so I might just even drop the HHVMCraft prefix and go with "Core/Networking/Packets....".

**Comment by lungyiing** [comment]
I'd recommend keeping the prefix to prevent conflicts with other packages.

In terms of autoloading, composer should do this for you - all you have to do is include the `vendor/autoloader.php` file in server.php and the rest of the classes should be autoloaded.

I'll have a quick look and try and get a PR sorted.

**Comment by andrewvy** [comment]
Ah right, I forgot about the namespacing issues it could cause.

If you do take a look at it, thanks for your time! :)

**Comment by lungyiing** [comment]
https://github.com/andrewvy/HHVMCraft/pull/9
